### ISSUE TITLE
[object Object] could not be cloned.

### ISSUE THREAD

**Issue by williamqian** [socketio/socket.io-cluster-adapter#4]
![image](https://user-images.githubusercontent.com/19399075/173049505-0c688dad-482f-4c18-b147-719463640c26.png)

**Comment by darrachequesne** [comment]
Hi!

We will need a bit more information for this. What kind of data are you sending? Does it contain circular references?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
