### ISSUE TITLE
io.local.emit fails but io.local.fetchSockets works

### ISSUE THREAD

**Issue by wvhulle** [socketio/socket.io-cluster-adapter#7]
I am using Socket.IO client and server 4.5.3 together with cluster adapter 0.2.1 and sticky 1.0.2.

When I do io.local.emit from a node (child worker) in the cluster, nothing happens. It seems like the emit doesn't work. 

When I replace the emit by a loop over the result of io.local.fetchSockets, it does works. This seems like a bug. I cannot find anything online about people using io.local.

**Comment by darrachequesne** [comment]
Hi! `io.local.emit()` will only emit to clients that are connected to the given worker.

I was not able to reproduce the issue, could you please check with the basic example [there](https://github.com/socketio/socket.io-fiddle/tree/cluster-adapter)?

**Comment by wvhulle** [comment]
Hi thanks for the repo. The repo seems to run fine. I think I have found what the issue is. I am making a process.on("message") listener and inside that listener I am emitting locally. I think that the problem here is that local.emit makes use of the process.on("message") to emit but I am overwriting the listener. Is there a way to recycle or extend the default listener so i can still listen for events with process.on in a worker and emit locally?

**Comment by darrachequesne** [comment]
Do you think there Is something we can fix on our end? Could you please provide a way to reproduce the issue (by forking the [fiddle project](https://github.com/socketio/socket.io-fiddle/tree/cluster-adapter) for example)?

**Comment by wvhulle** [comment]
I will try to send you a minimal example. Is there a reason why the branch you send in above message has a multithreaded client? It seems like the other branches just have a single threaded one and a multithreaded server.

**Comment by introspection3** [comment]
Error: timeout reached: only 0 responses
