### ISSUE TITLE
Dependency on socket.io-adapter@2.4.0 should be upgraded to socket.io-adapter@2.5.2

### ISSUE THREAD

**Issue by wvhulle** [socketio/socket.io-cluster-adapter#8]
Hi, I think something went wrong during a recent upgrade.

The function createAdapter() from @socket.io/cluster-adapter@0.2.1 returns `(nsp: any) => ClusterAdapter` where `ClusterAdapter` extends `Adapter` from `socket.io-adapter@2.4.0`. However, `server.adapter` from socket.io@4.6.1 expects Adapter from `socket.io-adapter@2.5.2`. There are large differences between these two classes.

```
Type 'ClusterAdapter' is missing the following properties from type 'Adapter': _encode, persistSession, restoreSession ...... 
```

**Comment by RaenonX** [comment]
Having the same issue here. @darrachequesne could you advise?

Thanks for the work here btw.

**Comment by darrachequesne** [comment]
Done in https://github.com/socketio/socket.io-cluster-adapter/commit/15fd56e78d52aa65c5fbf412dec57ab4bdaee7cc, and included in version [0.2.2](https://github.com/socketio/socket.io-cluster-adapter/releases/tag/0.2.2).

**Comment by wvhulle** [comment]
Thanks for the work! Are you the only contributor?

**Comment by darrachequesne** [comment]
@wvhulle yes, I'm currently the only active contributor.
