### ISSUE TITLE
error when npm install @socket.io/cluster-adapter

### ISSUE THREAD

**Issue by syndronize** [socketio/socket.io-cluster-adapter#9]
At line:1 char:13
+ npm install @socket.io/cluster-adapter
+             ~~~~~~~
The splatting operator '@' cannot be used to reference variables in an
expression. '@socket' can be used only as an argument to a command. To
reference variables in an expression use '$socket'.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorReco
   rdException
    + FullyQualifiedErrorId : SplattingNotPermitted
![Screenshot 2023-10-19 165609](https://github.com/socketio/socket.io-cluster-adapter/assets/58931805/972575c2-0b03-4dce-af02-1f3f27047453)

**Comment by darrachequesne** [comment]
For future readers:

On Windows systems, you need to escape the `@` character:

```bash
npm install '@socket.io/cluster-adapter'
```

Reference: https://stackoverflow.com/a/59807392/5138796
